name: Github Pages Build 🏗

on:
  push:
    branches:
    - main
    
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    container:
      image: 'swift:5.5'
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - name: Install updated GLIBC
        run: |
          curl -fsSL http://ftp.gnu.org/gnu/libc/glibc-2.28.tar.gz -o glibc-2.28.tar.gz
          tar -xzf glibc-2.28.tar.gz
          cd glibc-2.28
          mkdir build
          cd build
          ../configure --prefix=/usr
          make -j$(nproc)
          sudo make install
          
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build Swift Saga📱
        run: swift run
        
      - name: Deploy 🌍
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          cname: www.swiftmiss.fun
          publish_branch: gh-pages
