name: Github Pages Build 🏗

on:
  push:
    branches:
    - main
    
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    container:
      image: 'swift:5.5'
    steps:
    
      - name: Setup Node.js
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        uses: actions/checkout@v4
        uses: actions/checkout@v4.2.0
        uses: actions/checkout@main
          
   #   - name: Checkout
    #    uses: actions/checkout@v3
        
      - name: Build Swift Saga📱
        run: swift run
        
      - name: Deploy 🌍
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          cname: www.swiftmiss.fun
          publish_branch: gh-pages
